# Generated by Django 2.1.5 on 2019-02-06 23:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_driver', models.BooleanField(blank=True, null=True)),
                ('license_plate_number', models.CharField(blank=True, max_length=30, verbose_name='License Plate Number')),
                ('Vehicle_Capacity', models.IntegerField(default=0, verbose_name='Maxmium Number of Passengers Allowed')),
                ('Vehicle_Model', models.CharField(blank=True, max_length=30, verbose_name='Vehicle_Model')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Destination', models.CharField(max_length=200)),
                ('sharer', models.CharField(default='', max_length=200)),
                ('driver', models.CharField(default='', max_length=200)),
                ('Arrival_Time', models.DateTimeField()),
                ('Num_Passenger', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('Num_Sharer', models.IntegerField(default=0)),
                ('Ride_status', models.CharField(choices=[('Open', 'Open'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed')], default='Open', max_length=10)),
                ('Vehicle_type', models.CharField(blank=True, max_length=50, null=True)),
                ('Special_request', models.CharField(blank=True, max_length=200, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Destination', models.CharField(max_length=200)),
                ('Arrival_Time_0', models.DateTimeField(default='2018-02-05 12:00', help_text='Format: 2019-02-05 12:00', verbose_name='Earliest Acceptable Arrival Time')),
                ('Arrival_Time_1', models.DateTimeField(default='2019-02-05 12:00', help_text='Format: 2019-02-05 12:00', verbose_name='latest Acceptable Arrival Time')),
                ('Num_Passenger', models.IntegerField(default=1)),
                ('sharer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
